### ISSUE TITLE
confluence 8091 port is not run

### ISSUE THREAD

**Issue by linux0x5c** [Praqma/ask#7]
I set Datacenter.Enabled: true,I install confluence data center with confluence helm chart,but 8091 port is not run.
logs:
DATACENTER_MODE is set to 'true' and CONFLUENCE_DATACENTER_SHARE is found set to: /var/atlassian/confluence-datacenter/
Proceeding to setup Confluence in DataCenter mode...
The file /var/atlassian/application-data/confluence/confluence.cfg.xml was not found; because, this may be the first node - still booting up.

**Comment by hoeghh** [comment]
Could you post your values file and what you expected to happen?

**Comment by linux0x5c** [comment]
Hi, @hoeghh 
I now set the replicaset in values.yaml to 1, I successfully completed the confluence cluster, but when I set the replicaset in values.yaml to 2 and upgraded the cluster with helm, the new node did not join the previous cluster, do I need to change anything manually now?

**Comment by linux0x5c** [comment]
![conf](https://user-images.githubusercontent.com/35218713/70425411-1ce9c180-1aac-11ea-8f00-b1ad046e1089.jpg)

**Comment by linux0x5c** [comment]
When i access confluence,it seem to create a new cluster.

**Comment by hoeghh** [comment]
Hi, that is because you need to clone the home folder volume from node 1, to node 2, before scaling.
The data center volume needs to support RWX as well for this to work. @linux0x5c

**Comment by hoeghh** [comment]
Also, remember to have sticky session enabled on the loadbalancer.

**Comment by linux0x5c** [comment]
Hi, @hoeghh ,I'm glad to have your help,my data center volume needs to support RWX,mysql loadbalancer support sticky session,do I need to stop the node before I scaling it?

**Comment by linux0x5c** [comment]
When I clone the home folder volume from node 1, to node 2, someting is wrong in this page.


[Origin node: d5f02268 listening on /172.16.0.66:5801] Clustered Confluence: Database is being updated by an instance which is not part of the current cluster. You should check network connections between cluster nodes, especially multicast traffic.

confluence node logs:
10-Dec-2019 00:02:57.937 SEVERE [http-nio-8090-exec-10] org.apache.catalina.core.StandardHostValve.custom Exception Processing ErrorPage[errorCode=500, location=/500page.jsp]
	org.apache.jasper.JasperException: An exception occurred processing [/500page.jsp] at line [120]

117: 
118:         	if (sysInfoService != null)
119:         	{
120: 	        	confluenceInfo = sysInfoService.getConfluenceInfo();
121: 	        	memoryInfo = sysInfoService.getMemoryInfo();
122: 	        	dbInfo = sysInfoService.getSafeDatabaseInfo();
123:                 sysinfo = GeneralUtil.convertBeanToMap(sysInfoService.getSystemProperties());


Stacktrace:
		at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:625)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:514)
		at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
		at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.confluence.web.filter.DebugFilter.doFilter(DebugFilter.java:46)
		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.johnson.plugin.servlet.filter.JohnsonServletFilterModuleContainerFilter.doFilter(JohnsonServletFilterModuleContainerFilter.java:47)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
		at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
		at com.atlassian.confluence.util.profiling.ProfilingSiteMeshFilter.doFilter(ProfilingSiteMeshFilter.java:50)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.johnson.plugin.servlet.filter.JohnsonServletFilterModuleContainerFilter.doFilter(JohnsonServletFilterModuleContainerFilter.java:47)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.confluence.web.filter.ConfluenceSecurityFilter.doFilter(ConfluenceSecurityFilter.java:27)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.seraph.filter.BaseLoginFilter.doFilter(BaseLoginFilter.java:148)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.johnson.plugin.servlet.filter.JohnsonServletFilterModuleContainerFilter.doFilter(JohnsonServletFilterModuleContainerFilter.java:47)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.johnson.plugin.servlet.filter.JohnsonServletFilterModuleContainerFilter.doFilter(JohnsonServletFilterModuleContainerFilter.java:47)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.confluence.util.RequestCacheThreadLocalFilter.doFilter(RequestCacheThreadLocalFilter.java:59)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.github.kristofa.brave.servlet.BraveServletFilter.doFilter(BraveServletFilter.java:59)
		at com.atlassian.confluence.web.filter.ZipkinTracingFilter.doFilter(ZipkinTracingFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at com.atlassian.confluence.web.filter.DebugFilter.doFilter(DebugFilter.java:46)
		at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:712)
		at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:461)
		at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
		at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
		at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:394)
		at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:253)
		at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:348)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:173)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1579)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
	Caused by: java.util.concurrent.CompletionException: org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
		at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:824)
		at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:834)
		at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2155)
		at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:110)
		at com.atlassian.confluence.impl.concurrency.CompletionStageUtils.foldResult(CompletionStageUtils.java:19)
		at com.atlassian.confluence.impl.vcache.SynchronousExternalCache.get(SynchronousExternalCache.java:236)
		at com.atlassian.confluence.setup.bandana.ConfluenceCachingBandanaPersister.retrieve(ConfluenceCachingBandanaPersister.java:78)
		at com.atlassian.confluence.setup.bandana.ConfluenceCachingBandanaPersister.retrieve(ConfluenceCachingBandanaPersister.java:71)
		at com.atlassian.bandana.DefaultBandanaManager.getValue(DefaultBandanaManager.java:32)
		at com.atlassian.bandana.DefaultBandanaManager.getValue(DefaultBandanaManager.java:24)
		at com.atlassian.confluence.core.DatabaseSidManager.getSid(DatabaseSidManager.java:44)
		at com.atlassian.confluence.status.service.DefaultSystemInformationService.getConfluenceInfo(DefaultSystemInformationService.java:117)
		at org.apache.jsp._500page_jsp._jspService(_500page_jsp.java:309)
		at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
		at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:476)
		... 63 more
	Caused by: org.springframework.transaction.CannotCreateTransactionException: Could not open Hibernate Session for transaction; nested exception is com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
		at org.springframework.orm.hibernate.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:473)
		at com.atlassian.confluence.impl.hibernate.ConfluenceHibernateTransactionManager.doBegin(ConfluenceHibernateTransactionManager.java:41)
		at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:378)
		at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
		at com.sun.proxy.$Proxy75.getTransaction(Unknown Source)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:475)
		at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:289)
		at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
		at com.sun.proxy.$Proxy76.retrieve(Unknown Source)
		at com.atlassian.confluence.setup.bandana.ConfluenceCachingBandanaPersister.lambda$retrieve$0(ConfluenceCachingBandanaPersister.java:80)
		at com.atlassian.confluence.impl.vcache.SynchronousExternalCache.lambda$get$11(SynchronousExternalCache.java:239)
		at com.atlassian.confluence.impl.concurrency.CompletionStageUtils.lambda$foldResult$0(CompletionStageUtils.java:19)
		at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
		... 78 more
	Caused by: com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!
		at com.hazelcast.instance.HazelcastInstanceProxy.getOriginal(HazelcastInstanceProxy.java:315)
		at com.hazelcast.instance.HazelcastInstanceProxy.getCluster(HazelcastInstanceProxy.java:218)
		at com.hazelcast.hibernate.HazelcastTimestamper.nextTimestamp(HazelcastTimestamper.java:38)
		at com.hazelcast.hibernate.AbstractHazelcastCacheRegionFactory.nextTimestamp(AbstractHazelcastCacheRegionFactory.java:76)
		at com.atlassian.confluence.cache.hazelcast.hibernate.HazelcastHibernateRegionFactory.nextTimestamp(HazelcastHibernateRegionFactory.java:93)
		at com.atlassian.confluence.impl.cache.hibernate.ConfluenceRegionFactory.nextTimestamp(ConfluenceRegionFactory.java:58)
		at org.hibernate.internal.AbstractSharedSessionContract.<init>(AbstractSharedSessionContract.java:141)
		at org.hibernate.internal.AbstractSessionImpl.<init>(AbstractSessionImpl.java:29)
		at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:248)
		at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1202)
		at org.hibernate.internal.SessionFactoryImpl.openSession(SessionFactoryImpl.java:441)
		at com.atlassian.confluence.impl.core.persistence.hibernate.SwitchableCachingSessionFactory.openSession(SwitchableCachingSessionFactory.java:117)
		at sun.reflect.GeneratedMethodAccessor203.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:205)
		at com.sun.proxy.$Proxy74.openSession(Unknown Source)
		at com.atlassian.hibernate.adapter.bridge.factory.SessionFactoryV2orV5BridgeProxy.openSession(SessionFactoryV2orV5BridgeProxy.java:95)
		at org.springframework.orm.hibernate.HibernateTransactionManager.doBegin(HibernateTransactionManager.java:413)
		... 96 more

dear @hoeghh I dont't know what happend,can you help me?

**Comment by hoeghh** [comment]
When you install, choose tcp/ip for data center. then simply input the one ip of the first node, and continue the setup guide. You should not use the multicast option.

Let me know if that works.

**Comment by linux0x5c** [comment]
Hi, @hoeghh ,The IP address of my POD is not fixed, and the TCP/IP mode does not support domain name filling, so why not use multicast mode?

**Comment by hoeghh** [comment]
Hi,

I know, the pod ip will change everytime you create a new one. 

When you install, choose tcp/ip and enter the ip showing for the current pod. 
In our containers, we have an entrypoint script that finds the ip's of the other ready pods, and add them to the configuration of tcp/ip. That way, new pods will always find the existing ones and join the cluster. 

so.
1. Install node-0 and go through the guide with tcp-ip
2. Copy the home folder of node-0 to node-1
3. Scale the statefulset to 2
4. Check the `confluence.cluster.peers` section in the file `confluence.cfg.xml` in each home folder (for node-0 and node-1).
5. post your values file and 2x confluence.cfg.xml after scaling here if it doesnt work. (clean it for database passwords before doing so)

A long time ago (before helm) i made this video, where is installed and scaled Confluence in ASK. The only thing i didn't show, was to copy the home folder before scaling. Maybe its worth watching.
https://www.youtube.com/watch?v=0yUvCZXqPZI

**Comment by linux0x5c** [comment]
@hoeghh Hi,I am very glad that you have patiently solved the problem. I successfully started the confluence cluster according to your method. Thank you very much.
